feat: add authorization check for workflow execution

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -10,6 +10,12 @@ jobs:
         name: Run tests
         runs-on: ubuntu-latest
         steps:
+            - name: Check user running the workflow
+              if: github.event_name == 'workflow_dispatch' && github.actor != 'franjefriten'
+              run: |
+                  echo "Error running workflow! ${{ github.actor }} has no authorization"
+                  exit 1
+
             - name: Checkout code
               uses: actions/checkout@v4
 
